services:
  - type: web
    name: codeworks-license
    runtime: node
    plan: free
    rootDir: license-server
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:NyEIDqOD7LafesI9@db.oxaxwgklluykwkqrxqsf.supabase.co:5432/postgres?sslmode=require
      - key: ADMIN_KEY
        value: CW-Admin-717c82ed7aaf43aab2eaadc194328630
      - key: TOKEN_SECRET
        value: nwQCvOOM8VcDgMfqgLwEtKAmJhfWmMurBduo4auadNE=
